main: "${project.groupId}.${project.name}"
name: "${project.name}"
version: "${project.version}"
author: JustEli
website: "${project.url}"
api-version: "1.14"
loadbefore:
  - GriefPrevention
  - WorldGuard